import type { LucideIcon } from "lucide-react";
import {
    ShieldCheck,
    Store,
    Package,
    ShoppingCart,
    Users,
    CalendarClock,
    BarChart3,
    Wallet,
    Settings2,
    Smartphone,
    Lock,
    LayoutDashboard,
    Calendar,
} from "lucide-react";

export const projectFeatureIcons: Record<string, LucideIcon> = {
    Authentication: Lock,
    Dashboard: LayoutDashboard,
    "Products Management": Package,
    Products: Package,
    "Orders Management": ShoppingCart,
    Orders: ShoppingCart,
    Categories: Store,
    Reports: BarChart3,
    "Responsive Design": Smartphone,
    Events: Calendar,
    "Events Management": Calendar,
    Reservations: CalendarClock,
    Users: Users,
    "Users Management": Users,
    "Multi-Store Management": Store,
    Employees: Users,
    Schedules: CalendarClock,
    Finance: Wallet,
    "Roles & Permissions": ShieldCheck,
    Settings: Settings2,
    "Responsive Dashboard": Smartphone,
};